config/routes.rb
Rails.application.routes.draw do
  #root to: "welcome#index"
  #root to: "homes#index"
  root to: "public/articles#index"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  resources :user_profiles do
    get "/comments" => "user_profiles#comments", as: :user_comments, on: :member
    get "/contexts" => "user_profiles#contexts", as: :user_contexts, on: :member
    get "/authors" => "user_profiles#authors", as: :user_authors, on: :member
    get "/articles" => "user_profiles#articles", as: :user_articles, on: :member
  end

  resources :homes, only: [:index] do
    get '/set_layout/:layout_name' => "homes#set_layout", as: :set_layout, on: :collection
  end

  resources :articles do
    get   "/tags" => "articles#tags", as: :tags, on: :member
    post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member
    get "/export_pdf" => "articles#article_pdf", as: :export_pdf, on: :member
    get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    get "/contribution/new" => "articles#contributed_article_new", as: :contributed_article_new, on: :collection
    post "contribution/create" => "articles#contributed_article_create", as: :contributed_article_create, on: :collection
  end

  resources :comments

  resources :themes do
    get "/theme_chapters/new" => "theme_chapters#new", as: :new_theme_chapter#, on: :member
    get "/add_articles_page" => "themes#add_articles_page", as: :add_articles_page , on: :member
    post "/add_article_in_theme" => "themes#add_article_in_theme", as: :add_article_in_theme, on: :member
    post "/remove_article_from_theme" => "themes#remove_article_from_theme", as: :remove_article_from_theme, on: :member
    get "/search_articles" => "themes#search_articles", as: :search_articles, on: :collection
  end
  resources :authors do
    get "/autocomplete_term" => "authors#autocomplete_term", as: :autocomplete_term, on: :collection
  end
  resources :theme_chapters
  resources :comment_reportings, only: [:index, :destroy, :create]
  post "comment_reportings/:comment_id/mark_as_read" => "comment_reportings#mark_as_read", as: :mark_as_read
  resources :tags
  resources :panchangs, only: [:index, :show] do
    get "/pdf/export" => "panchangs#panchang_pdf", as: :export_pdf, on: :member
  end
  
  resources :stories
  resources :search, only: [] do
    get "/autocomplete_term" => "search#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/articles" => "search#search_articles", as: :search_articles, on: :collection
  end

  namespace :admin do
    resources :dashboards, only: [:index] do
    end
    resources :user_mgmts, only: [:index, :show, :destroy] do
      post "/block_to_user" => "user_mgmts#block_to_user", as: :block_to_user, on: :member
      post "/unblock_to_user" => "user_mgmts#unblock_to_user", as: :unblock_to_user, on: :member
      get "/blocked_users" => "user_mgmts#blocked_users", as: :blocked_users, on: :collection
    end
    resources :article_types
    resources :contexts
    resources :articles, only: [:index, :show, :edit, :update, :destroy] do
      get   "/tags" => "articles#tags", as: :tags, on: :member
      post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member

      get "/approved" => "articles#approved", as: :approved_articles, on: :collection
      get "/pending" => "articles#pending", as: :pending_articles, on: :collection
      get "/rejected" => "articles#rejected", as: :rejected_articles, on: :collection
      post "/approve" => "articles#approve", as: :approve, on: :member
      post "/reject" => "articles#reject", as: :reject, on: :member
      
      get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
      get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    end
    resources :authors, only: [:index, :show, :edit, :update, :destroy] do
      get "/approved" => "authors#approved", as: :approved_authors, on: :collection
      get "/pending" => "authors#pending", as: :pending_authors, on: :collection
      post "/approve" => "authors#approve", as: :approve, on: :member
      post "/reject" => "authors#reject", as: :reject, on: :member
      post "/merge" => "authors#merge", as: :merge, on: :member
      post "/mark_as_sant" => "authors#mark_as_sant", as: :mark_as_sant, on: :member
      post "/remove_from_sant" => "authors#remove_from_sant", as: :remove_from_sant, on: :member
    end
    resources :reports, only: [:index] do
      get '/articles_report' => "reports#articles_report", as: :articles_report, on: :collection
      get '/authors_report' => "reports#authors_report", as: :authors_report, on: :collection
      get '/contexts_report' => "reports#contexts_report", as: :contexts_report, on: :collection
    end

    resources :tags, only: [:index, :show, :edit, :update, :destroy] do
      post "/reject" => "tags#reject", as: :reject, on: :member
      post "/approve" => "tags#approve", as: :approve, on: :member
      get "/approved" => "tags#approved", as: :approved_tags, on: :collection
      get "/rejected" => "tags#rejected", as: :rejected_tags, on: :collection
      post '/convert_tag_to_context' => "tags#convert_tag_to_context", as: :tag_to_context, on: :member
    end

    resources :suggestions, only: [:index, :show] do
      get "/approve" => "suggestions#approve", as: :approve, on: :member
      get "/reject" => "suggestions#reject", as: :reject, on: :member
      get "/approved" => "suggestions#approved", as: :approved, on: :collection
      get "/rejected" => "suggestions#rejected", as: :rejected, on: :collection
    end

    resources :panchangs do
      # get '/get_tithis' => "panchangs#get_tithis", on: :collection

      post '/populate_panchang' => "panchangs#populate_panchang", on: :member, as: :populate_panchang
      post '/add_purshottam_mas' => "panchangs#add_purshottam_mas", on: :member, as: :add_purshottam_mas
      post '/remove_purshottam_mas' => "panchangs#remove_purshottam_mas", on: :member, as: :remove_purshottam_mas

      resources :panchang_tithis do
        get '/:month_id/get_tithis' => "panchang_tithis#get_tithis", as: :get_tithis, on: :collection
      end
    end

    resources :scriptures do
      get "/chapters/new" => "chapters#new", as: :chapters_new
    end

    resources :compiled_scriptures, only: [:index, :show] do
      get '/get_articles' => "compiled_scriptures#get_articles", as: :get_articles
      get '/add_articles_page' => "compiled_scriptures#add_articles_page", as: :add_articles_page
      post '/add_article' => "compiled_scriptures#add_article", as: :add_articles
      post '/remove_article' => "compiled_scriptures#remove_article", as: :remove_articles
      get '/search_articles' => "compiled_scriptures#search_articles", as: :search_articles, on: :collection

      get '/scriptures_for_indexing' => "compiled_scriptures#scriptures_for_indexing", as: :scriptures_for_indexing, on: :collection
      get '/:scripture_id/edit_article_index' => "compiled_scriptures#edit_article_index", as: :edit_article_index, on: :collection
      get '/get_chapter_articles' => "compiled_scriptures#get_chapter_articles", as: :get_chapter_articles
      get '/update_articles_index' => "compiled_scriptures#update_articles_index", as: :update_articles_index
      
      get '/get_indexed_articles' => "compiled_scriptures#get_indexed_articles", as: :get_indexed_articles
      post '/update_article_index' => "compiled_scriptures#update_article_index", as: :update_article_index
    end

    resources :chapters do 
      get '/get_sections' => "chapters#get_sections", as: :get_sections, on: :collection
      get '/get_section_chapters' => "chapters#get_section_chapters", as: :get_section_chapters, on: :collection
      get '/add_section_chapters' => "chapters#add_section_chapters", as: :add_section_chapters, on: :collection
      get '/remove_section_chapters' => "chapters#remove_section_chapters", as: :remove_section_chapters, on: :collection
      post '/add_chapters_in_section' => "chapters#add_chapters_in_section", as: :add_chapters_in_section, on: :collection
      post '/remove_chapters_from_section' => "chapters#remove_chapters_from_section", as: :remove_chapters_from_section, on: :collection
    end
    resources :scripture_articles do
      get '/get_chapters' => "scripture_articles#get_chapters", as: :get_chapters, on: :collection
      get '/get_index' => "scripture_articles#get_index", as: :get_index, on: :collection
      get '/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      # get '/:scripture_type/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      post '/update_article_index' => "scripture_articles#update_article_index", as: :update_article_index, on: :collection
      get '/get_chapter_articles' => "scripture_articles#get_chapter_articles", as: :get_chapter_articles, on: :collection
    end

    resources :strota do 
      resources :strota_articles do 
        # get '/add_aarti' => 'strota_articles#new', as: :add_aarti, on: :member
        # get '/get_strota_articles' => 'strota_articles#get_strota_articles', as: :get_strota_articles, on: :member
        # get '/get_index' => "strota_articles#get_index", as: :get_index, on: :collection
        get '/edit_article_index' => "strota_articles#edit_article_index", as: :edit_article_index, on: :collection
        post '/update_article_index' => "strota_articles#update_article_index", as: :update_article_index, on: :member
      end
    end
  end

  namespace :public, path: :pb do

    resources :articles, only: [:index, :show] do

app/models/context.rb
class Context < ApplicationRecord
  has_many :articles
  belongs_to :theme, optional: true
  belongs_to :user, optional: true

  scope :pending, ->() { where(is_approved: false) }
  scope :approved, ->() { where(is_approved: true) }
  paginates_per 10

  validates :name, presence: true

end

app/controllers/admin/contexts_controller.rb
class Admin::ContextsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :set_context, only: %i[ show edit update destroy ]

  # GET /contexts or /contexts.json
  def index
    @contexts = Context.order("created_at DESC").page(params[:page])
  end

  # GET /contexts/1 or /contexts/1.json
  def show
  end

  # GET /contexts/new
  def new
    @context = Context.new(is_approved: true)
  end

  # GET /contexts/1/edit
  def edit
  end

  # POST /contexts or /contexts.json
  def create
    params[:context][:name] = params[:context][:name].strip
    params[:context][:is_approved] = true
    @context = current_user.contexts.new(context_params)

    respond_to do |format|
      if @context.save
        format.html { redirect_to admin_contexts_url(), notice: "Context was successfully created." }
        format.json { render :show, status: :created, location: @context }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contexts/1 or /contexts/1.json
  def update
    respond_to do |format|
      if @context.update(context_params)
        format.html { redirect_to admin_contexts_url(), notice: "Context was successfully updated." }
        format.json { render :show, status: :ok, location: @context }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contexts/1 or /contexts/1.json
  def destroy
    @context.destroy

    respond_to do |format|
      format.html { redirect_to admin_contexts_url, notice: "Context was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_context
      @context = Context.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def context_params
      params.fetch(:context, {}).permit(:name, :is_approved, :user_id)
    end

    def verify_admin
      if !current_user.is_admin && !current_user.is_super_admin
        redirect_back_or_to homes_path
      end
    end
end

app/helpers/admin/contexts_helper.rb
module Admin::ContextsHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/admin/contexts/_context.html.erb
<table class="table">
  <thead class="table-primary">
    <tr>
      <th>S. No.</th>
      <th scope="col">प्रसंग नाम</th>
      <th class="d-none d-xl-table-cell">स्वीकृत/अस्वीकृत </th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if contexts.present? %>
      <%
        page = (contexts.current_page - 1)
        per_page = contexts.present? ? contexts.limit_value : 0
      %>
      <% contexts.each_with_index do |context, index| %>
        <% ind = (page * per_page) + (index + 1) %>
        <tr>
					<th scope="row">
						<%= ind %>
					</th>
					<td>
						<%= link_to "" do %>
							<%= context.name %>
						<% end %>
					</td>
					<td class="d-none d-xl-table-cell">
						<%= context.is_approved ? 'स्वीकृत' : 'लंबित' %>
					</td>
					<td>
						<div class="row">
              <% if context.name != "अन्य" %>
  							<div class="col-md-2">
  								<%= link_to edit_admin_context_path(context) do %>
  								  <i class="fa fa-edit"></i>
  								<% end %>
  							</div>
  							<div class="col-md-2">
  								<%= form_for([:admin, context], html: { method: :delete, onSubmit: "return confirm('Are you sure you wish to delete?');" }) do |f| %>
  						      <button type="submit" class="btn" style="padding: 0;margin-bottom: 1px;">
  						        <i class="fa fa-trash" style="color:red;"></i>
  						      </button>
  						    <% end %>
  						  </div>
              <% end %>
				    </div>
					</td>
				</tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="3">
          <center>अभी कोई डाटा उपलब्ध नहीं है</center>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if paginate(contexts).present? %>
  <%= paginate contexts, remote: true %>
  <div class="dropdown-divider"></div>
<% end %>
<%= link_to "प्रसंग जोड़े", new_admin_context_path %>

app/views/admin/contexts/_form.html.erb
<%= form_with(model: [:admin, context], html: {
  'data-context-target': 'form', 'data-action': 'context#submitForm'}) do |form| %>
  <div class="row">
    <div class="col-md-8">
      <div class="mb-3 alert alert-danger alert-dismissible fade show" style="display:  <%= context.errors.present? ? 'block' : 'none' %>;" role="alert">
        <% context.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        <button type="button" class="btn-close" onclick="$('.alert').hide()" aria-label="Close" style="font-size: 12px; "></button>
      </div>

      <div class='mb-3'>
        <label class='form-label'>
          नाम <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
        </label>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class='text-center mt-3 actions'>
        <div class="row">
          <div class="col-md-4">
            <% if form.object.id.blank? %>
              <%= form.submit "प्रसंग जोड़े", class: 'btn btn-lg btn-primary form-control' %>
            <% else %>
              <%= form.submit "प्रसंग अद्यतन करे", class: 'btn btn-lg btn-primary form-control' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/contexts/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          प्रसंग अद्यतन फॉर्म
        </div>
        <div class="dropdown-divider"></div>
        <div class="m-sm-4" data-controller= 'author'>
          <!-- <h3 class="card-title">New article</h3>
          <div class="dropdown-divider"></div> -->
          <%= render "form", context: @context %>
        </div>
        <div class="dropdown-divider"></div>
        <%#= link_to "प्रसंग देखे", @context %>
        <%= link_to "प्रसंग सूची देखे", admin_contexts_path %>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/context-custom" %>
<% end %>

app/views/admin/contexts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body h-100">
        <div class="col-md-12 page-subject-header">
          प्रसंग सूची 
        </div>
        <div class="dropdown-divider"></div>
        <%= render partial: 'context', locals: {contexts: @contexts } %>
      </div>
    </div>
  </div>
</div>

app/views/admin/contexts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          प्रसंग फॉर्म
        </div>
        <div class="dropdown-divider"></div>
        <div class="m-sm-4" data-controller= 'article'>
          <%= render "form", context: @context %>
        </div>
        <div class="dropdown-divider"></div>
        <%= link_to "प्रसंग सूची देखे", admin_contexts_path %>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/context-custom" %>
<% end %>

app/views/admin/contexts/pending_contexts.html.erb
<div class="row" data-controller="dashboard">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body h-400">
				<span class="col-md-6 text-start article-title text-primary">
		      लंबित प्रसंग सूची 
		    </span>
		    <div class="dropdown-divider"></div>  
      	<input type=hidden name="authenticity_token" value="<%= form_authenticity_token %>" data-target="dashboard.csrfToken">
      	<div id="pending_context_list">
      		<%= render "context", contexts_pending: @contexts_pending, contexts_approved: @contexts_approved %>
      	</div>
      	<div id="paginate-block">
      		<%#= page_entries_info @contexts_pending %>
      		<%= paginate @contexts_pending, remote: true %>
      	</div>
      	<!-- Modal -->
	      <div class="modal fade" id="updateContextPopup" tabindex="-1" aria-labelledby="updateContextPopupLabel" aria-hidden="true">
	        <div class="modal-dialog">
	          <div class="modal-content">
	            <div class="modal-header">
	              <h3 class="modal-title" id="exampleModalLabel">
	                प्रसंग का नाम अपडेट करे 
	              </h3>
	              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	            </div>
	            <div class="modal-body">
	              <div class="mb-3">
	                <label for="formFile" class="form-label">प्रसंग का नया नाम</label>
	                <%= text_field_tag 'update_context_name', '', class:"form-control", 'data-dashboard-target': 'newContextName' %>
	              </div>
	            </div>
	            <div class="modal-footer">
	              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	              <button type="button" data-dashboard-target="saveContextBtn" data-index="" data-action="click->dashboard#updateContext" class="btn btn-primary">Save changes</button>
	            </div>
	          </div>
	        </div>
	      </div>
			</div>
		</div>
	</div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/dashboard/context-custom" %>
<% end %>

app/views/admin/contexts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @context %>

<div>
  <%= link_to "Edit this context", edit_context_path(@context) %> |
  <%= link_to "Back to contexts", contexts_path %>

  <%= button_to "Destroy this context", @context, method: :delete %>
</div>