config/routes.rb
Rails.application.routes.draw do
  #root to: "welcome#index"
  #root to: "homes#index"
  root to: "public/articles#index"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  resources :user_profiles do
    get "/comments" => "user_profiles#comments", as: :user_comments, on: :member
    get "/contexts" => "user_profiles#contexts", as: :user_contexts, on: :member
    get "/authors" => "user_profiles#authors", as: :user_authors, on: :member
    get "/articles" => "user_profiles#articles", as: :user_articles, on: :member
  end

  resources :homes, only: [:index] do
    get '/set_layout/:layout_name' => "homes#set_layout", as: :set_layout, on: :collection
  end

  resources :articles do
    get   "/tags" => "articles#tags", as: :tags, on: :member
    post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member
    get "/export_pdf" => "articles#article_pdf", as: :export_pdf, on: :member
    get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    get "/contribution/new" => "articles#contributed_article_new", as: :contributed_article_new, on: :collection
    post "contribution/create" => "articles#contributed_article_create", as: :contributed_article_create, on: :collection
  end

  resources :comments

  resources :themes do
    get "/theme_chapters/new" => "theme_chapters#new", as: :new_theme_chapter#, on: :member
    get "/add_articles_page" => "themes#add_articles_page", as: :add_articles_page , on: :member
    post "/add_article_in_theme" => "themes#add_article_in_theme", as: :add_article_in_theme, on: :member
    post "/remove_article_from_theme" => "themes#remove_article_from_theme", as: :remove_article_from_theme, on: :member
    get "/search_articles" => "themes#search_articles", as: :search_articles, on: :collection
  end
  resources :authors do
    get "/autocomplete_term" => "authors#autocomplete_term", as: :autocomplete_term, on: :collection
  end
  resources :theme_chapters
  resources :comment_reportings, only: [:index, :destroy, :create]
  post "comment_reportings/:comment_id/mark_as_read" => "comment_reportings#mark_as_read", as: :mark_as_read
  resources :tags
  resources :panchangs, only: [:index, :show] do
    get "/pdf/export" => "panchangs#panchang_pdf", as: :export_pdf, on: :member
  end
  
  resources :stories
  resources :search, only: [] do
    get "/autocomplete_term" => "search#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/articles" => "search#search_articles", as: :search_articles, on: :collection
  end

  namespace :admin do
    resources :dashboards, only: [:index] do
    end
    resources :user_mgmts, only: [:index, :show, :destroy] do
      post "/block_to_user" => "user_mgmts#block_to_user", as: :block_to_user, on: :member
      post "/unblock_to_user" => "user_mgmts#unblock_to_user", as: :unblock_to_user, on: :member
      get "/blocked_users" => "user_mgmts#blocked_users", as: :blocked_users, on: :collection
    end
    resources :article_types
    resources :contexts
    resources :articles, only: [:index, :show, :edit, :update, :destroy] do
      get   "/tags" => "articles#tags", as: :tags, on: :member
      post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member

      get "/approved" => "articles#approved", as: :approved_articles, on: :collection
      get "/pending" => "articles#pending", as: :pending_articles, on: :collection
      get "/rejected" => "articles#rejected", as: :rejected_articles, on: :collection
      post "/approve" => "articles#approve", as: :approve, on: :member
      post "/reject" => "articles#reject", as: :reject, on: :member
      
      get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
      get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    end
    resources :authors, only: [:index, :show, :edit, :update, :destroy] do
      get "/approved" => "authors#approved", as: :approved_authors, on: :collection
      get "/pending" => "authors#pending", as: :pending_authors, on: :collection
      post "/approve" => "authors#approve", as: :approve, on: :member
      post "/reject" => "authors#reject", as: :reject, on: :member
      post "/merge" => "authors#merge", as: :merge, on: :member
      post "/mark_as_sant" => "authors#mark_as_sant", as: :mark_as_sant, on: :member
      post "/remove_from_sant" => "authors#remove_from_sant", as: :remove_from_sant, on: :member
    end
    resources :reports, only: [:index] do
      get '/articles_report' => "reports#articles_report", as: :articles_report, on: :collection
      get '/authors_report' => "reports#authors_report", as: :authors_report, on: :collection
      get '/contexts_report' => "reports#contexts_report", as: :contexts_report, on: :collection
    end

    resources :tags, only: [:index, :show, :edit, :update, :destroy] do
      post "/reject" => "tags#reject", as: :reject, on: :member
      post "/approve" => "tags#approve", as: :approve, on: :member
      get "/approved" => "tags#approved", as: :approved_tags, on: :collection
      get "/rejected" => "tags#rejected", as: :rejected_tags, on: :collection
      post '/convert_tag_to_context' => "tags#convert_tag_to_context", as: :tag_to_context, on: :member
    end

    resources :suggestions, only: [:index, :show] do
      get "/approve" => "suggestions#approve", as: :approve, on: :member
      get "/reject" => "suggestions#reject", as: :reject, on: :member
      get "/approved" => "suggestions#approved", as: :approved, on: :collection
      get "/rejected" => "suggestions#rejected", as: :rejected, on: :collection
    end

    resources :panchangs do
      # get '/get_tithis' => "panchangs#get_tithis", on: :collection

      post '/populate_panchang' => "panchangs#populate_panchang", on: :member, as: :populate_panchang
      post '/add_purshottam_mas' => "panchangs#add_purshottam_mas", on: :member, as: :add_purshottam_mas
      post '/remove_purshottam_mas' => "panchangs#remove_purshottam_mas", on: :member, as: :remove_purshottam_mas

      resources :panchang_tithis do
        get '/:month_id/get_tithis' => "panchang_tithis#get_tithis", as: :get_tithis, on: :collection
      end
    end

    resources :scriptures do
      get "/chapters/new" => "chapters#new", as: :chapters_new
    end

    resources :compiled_scriptures, only: [:index, :show] do
      get '/get_articles' => "compiled_scriptures#get_articles", as: :get_articles
      get '/add_articles_page' => "compiled_scriptures#add_articles_page", as: :add_articles_page
      post '/add_article' => "compiled_scriptures#add_article", as: :add_articles
      post '/remove_article' => "compiled_scriptures#remove_article", as: :remove_articles
      get '/search_articles' => "compiled_scriptures#search_articles", as: :search_articles, on: :collection

      get '/scriptures_for_indexing' => "compiled_scriptures#scriptures_for_indexing", as: :scriptures_for_indexing, on: :collection
      get '/:scripture_id/edit_article_index' => "compiled_scriptures#edit_article_index", as: :edit_article_index, on: :collection
      get '/get_chapter_articles' => "compiled_scriptures#get_chapter_articles", as: :get_chapter_articles
      get '/update_articles_index' => "compiled_scriptures#update_articles_index", as: :update_articles_index
      
      get '/get_indexed_articles' => "compiled_scriptures#get_indexed_articles", as: :get_indexed_articles
      post '/update_article_index' => "compiled_scriptures#update_article_index", as: :update_article_index
    end

    resources :chapters do 
      get '/get_sections' => "chapters#get_sections", as: :get_sections, on: :collection
      get '/get_section_chapters' => "chapters#get_section_chapters", as: :get_section_chapters, on: :collection
      get '/add_section_chapters' => "chapters#add_section_chapters", as: :add_section_chapters, on: :collection
      get '/remove_section_chapters' => "chapters#remove_section_chapters", as: :remove_section_chapters, on: :collection
      post '/add_chapters_in_section' => "chapters#add_chapters_in_section", as: :add_chapters_in_section, on: :collection
      post '/remove_chapters_from_section' => "chapters#remove_chapters_from_section", as: :remove_chapters_from_section, on: :collection
    end
    resources :scripture_articles do
      get '/get_chapters' => "scripture_articles#get_chapters", as: :get_chapters, on: :collection
      get '/get_index' => "scripture_articles#get_index", as: :get_index, on: :collection
      get '/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      # get '/:scripture_type/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      post '/update_article_index' => "scripture_articles#update_article_index", as: :update_article_index, on: :collection
      get '/get_chapter_articles' => "scripture_articles#get_chapter_articles", as: :get_chapter_articles, on: :collection
    end

    resources :strota do 
      resources :strota_articles do 
        # get '/add_aarti' => 'strota_articles#new', as: :add_aarti, on: :member
        # get '/get_strota_articles' => 'strota_articles#get_strota_articles', as: :get_strota_articles, on: :member
        # get '/get_index' => "strota_articles#get_index", as: :get_index, on: :collection
        get '/edit_article_index' => "strota_articles#edit_article_index", as: :edit_article_index, on: :collection
        post '/update_article_index' => "strota_articles#update_article_index", as: :update_article_index, on: :member
      end
    end
  end

  namespace :public, path: :pb do

    resources :articles, only: [:index, :show] do

app/controllers/admin/compiled_scriptures_controller.rb
class Admin::CompiledScripturesController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :set_scripture, only: %i[add_articles_page add_article remove_article]

  def index
    @scripture_type = ScriptureType.where(name: "प्रचलित संकलन").first
    @scriptures = @scripture_type.scriptures
  end
  
  def show
    @scripture = Scripture.find(params[:id])
    @cs_articles = @scripture.cs_articles.joins(:article).order("index").page(params[:page])
  end

  def add_articles_page
    @article_types = ArticleType.all
    @contexts = Context.all
    @authors = Author.all
    # @added_articles = Kaminari.paginate_array(@scriptures.articles).page(params[:page])
    # articles_tmp = Article.where(queryy).where.not(id: added_articles_tmp).order("hindi_title ASC")
    # @articles = Kaminari.paginate_array(articles_tmp).page(params[:page])
    get_articles_by_params
  end

  def search_articles
    get_articles_by_params
    respond_to do |format|
      format.html {}
      format.js {}
    end
    render layout: false
  end

  def add_article
    is_article_exist = nil
    #if @scripture.compiled_scriptures.where({article_id: params[:compiled_scripture][:article_id]}).blank?
    params[:cs_article][:user_id] = current_user.id
    if params[:cs_article][:chapter_id].present? 
      @chapter = Chapter.find(params[:cs_article][:chapter_id])
      is_article_exist = @chapter.cs_articles.where({article_id: params[:cs_article][:article_id]})
    else
      is_article_exist = @scripture.cs_articles.where({article_id: params[:cs_article][:article_id]})
    end

    if is_article_exist.blank?
      # @compiled_scripture = current_user.compiled_scriptures.new(compiled_scripture_params)
      @cs_article = current_user.cs_articles.new(cs_article_params)

      if @cs_article.save!
        flash[:success] = "उत्सव में रचना सफलतापूर्वक जोड़ दी गई है."
      else
        flash[:error] = "उत्सव में रचना जोड़ने की प्रकिया असफल हो गई है."
      end
    else
      flash[:error] = "उत्सव में रचना पहले से जुडी हुई है."
    end
    get_articles_by_params

    respond_to do |format|
      format.html {}
      format.js {}
    end
    render layout: false
  end

  def remove_article
    @chapter = Chapter.find(params[:chapter_id]) rescue nil

    if @chapter.present?
      @article = @chapter.cs_articles.find(params[:cs_article_id])
    else
      @article = @scripture.cs_articles.find(params[:cs_article_id])
    end

    if @article && @article.destroy!
      flash[:success] = "उत्सव से रचना सफलतापूर्वक हटा दी गई है."
    else
      flash[:error] = "उत्सव में रचना हटाने की प्रकिया असफल हो गई है."
    end
    get_articles_by_params

    respond_to do |format|
      format.html {}
      format.js {}
    end
    render layout: false
  end


  def scriptures_for_indexing
    @scripture_type = ScriptureType.where(name: "प्रचलित संकलन").first
    @scriptures = @scripture_type.scriptures
  end

  def edit_article_index
    @scripture = Scripture.find(params[:scripture_id])
    if params[:indexed] == "true"
      @cs_articles = @scripture.cs_articles.where("index is not null").page(params[:page])
    else
      @cs_articles = @scripture.cs_articles.where("index is null").page(params[:page])
    end
  end

  def update_article_index
    @scripture = Scripture.find(params[:compiled_scripture_id])
    @cs_article = @scripture.cs_articles.find(params[:article_id]) rescue nil

    respond_to do |format|
      if @cs_article.blank? and params[:bulk_updation] == "true"
        indx = 1
        @scripture = Scripture.find(params[:compiled_scripture_id])
        chapters = @scripture.chapters.present? ? @scripture.chapters.order("index") : [@scripture]

        chapters.each do | chapter | 
          chapter.cs_articles.each do | cs_article |
            cs_article.update(index: indx)
            indx = indx + 1
          end
        end    
        format.html { redirect_to admin_compiled_scriptures_path, notice: "Scripture was successfully indexed." }
      elsif @cs_article.update({index: params[:article_index]})
        get_indexed_articles
        format.html { }
        format.js { render status: 200 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cs_article.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_chapter_articles
    @chapter = Chapter.find(params[:chapter_id]) rescue nil
    parent = @chapter.present? ? @chapter : Scripture.find(params[:compiled_scripture_id])
    @articles = parent.cs_articles.order("index ASC").page(params[:page])
  end

  def get_indexed_articles
    @chapter = Chapter.find(params[:chapter_id]) rescue nil
    parent = @chapter.present? ? @chapter : Scripture.find(params[:compiled_scripture_id])

    if params[:action_type] == "Indexed"
      @articles = parent.cs_articles.where("index is not null").order("index ASC").page(params[:page])
    elsif params[:action_type] == "Non-Indexed"
      @articles = parent.cs_articles.where("index is null").order("index ASC").page(params[:page])
    elsif params[:requested_data_type] == "Indexed"
      @articles = parent.cs_articles.where("index is not null").order("index ASC").page(params[:page])
    else
      @articles = parent.cs_articles.where("index is null").order("index ASC").page(params[:page])
    end
  end

  private

    def get_articles_by_params
      queryy = ''
      added_articles_tmp, articles_tmp = []
      if params[:chapter_id].present?
        added_articles_tmp = Chapter.find(params[:chapter_id]).cs_articles
      else
        added_articles_tmp = @scripture.cs_articles
      end

      @added_articles = Kaminari.paginate_array(added_articles_tmp).page(params[:page])
      added_articles_tmp = added_articles_tmp.blank? ? [] : added_articles_tmp.pluck(:article_id)
    
      if params[:search_type] == 'by_attribute'
        queryy = Article.by_attributes_query(params[:author_id], params[:context_id],
          params[:article_type_id], params[:theme_chapter_id], params[:contributor_id]
        )
       elsif params[:search_type] == 'by_id'
        queryy = "articles.id = #{params[:article_id]}"
      elsif params[:search_type] == 'by_term'
        search_term = params[:term].strip
        if params[:search_in] == "english"
          queryy = "LOWER(english_title) like '%#{search_term.downcase}%'"
        else
           queryy = "content like '%#{search_term}%'  or hindi_title like '%#{search_term}%'"
        end
      end

      articles_tmp = Article.where(queryy).where.not(id: added_articles_tmp).order("hindi_title ASC")

      @articles = Kaminari.paginate_array(articles_tmp).page(params[:page])
    end

    def set_scripture
      @scripture = Scripture.find(params[:compiled_scripture_id])
    end

    def cs_article_params
      params.fetch(:cs_article, {}).permit(:chapter_id, :scripture_id, :article_id)
    end

    def verify_admin
      if !current_user.is_admin && !current_user.is_super_admin
        redirect_back_or_to homes_path
      end
    end
end

app/helpers/admin/compiled_scriptures_helper.rb
module Admin::CompiledScripturesHelper
end

app/views/admin/compiled_scriptures/_article.html.erb
<%
  page = (articles.current_page - 1)
  page_size = articles.present? ? articles.limit_value : 0
%>
<% articles && articles.each_with_index do |article, index|%>
  <li class="list-group-item">
    <span class="fLeft" id="aritcle-title-<%= article.id %>">
      <strong><%= (page*page_size) + (index+1)%>.</strong> <%= article.hindi_title %>    
    </span>
    <span class="fRight add-article-icon" data-id="<%= article.id %>" data-action-name="addition"
      data-action="click->admin-cscripture#articlesAdditionDeletion" >
      <i class="fa-solid fa-angle-right pull-right"></i>
    </span>
  </li>
<% end %>
<br>
<div id="paginate-block">
  <% if params[:action] == "add_articles_page" %> 
    <%= paginate articles %>
  <% else %>
    <%= paginate articles, remote: true, :params => { controller: :'/admin/compiled_scriptures', action: :search_articles } %>
  <% end %>
</div>

app/views/admin/compiled_scriptures/_article_for_index_update.html.erb
<table class="table">
  <thead class="table-primary">
    <tr>
      <th>S. No.</th>
      <th>रचना</th>
      <th>अनुक्रम</th>
    </tr>
  </thead>
  <tbody>
    <% if cs_articles.present? %>
      <%
        page = (cs_articles.current_page - 1)
        per_page = cs_articles.present? ? cs_articles.limit_value : 0
      %>
      <% cs_articles.each_with_index do |scr_article, index| %>
        <% ind = (page * per_page) + (index + 1) %>
        <tr id="scr_article_<%= scr_article.id %>">
          <td scope="row">
            <%= ind %>
          </td>
          <td>
            <div class="" style="max-height: 50px; overflow: hidden;">
              <%=raw scr_article.article.content %>
            </div>
          </td>
          <td>
            <%= number_field_tag "index", scr_article.index, style: "width: 60px", 'data-admin-cscripture-target': 'articleIndex' %>
            <%= button_tag 'अनुक्रम अद्यतित करे', type:"button", class: "btn btn-primary", style:"display:inline-block;", 'data-articleId': scr_article.id,
              'data-action': 'click->admin-cscripture#updateArticleIndex' %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6">
          <center>अभी कोई डाटा उपलब्ध नहीं है</center>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if cs_articles.present? && paginate(cs_articles).present? %>
  <%= paginate cs_articles, remote: true %>
  <div class="dropdown-divider"></div>
<% end %>

app/views/admin/compiled_scriptures/_indexed_article.html.erb
<table class="table">
  <thead class="table-primary">
    <tr>
      <th>S.No.</th>
      <th>रचना</th>
      <th>अध्याय</th>
      <th>अनुक्रम</th>
    </tr>
  </thead>
  <tbody>
    <% if cs_articles.present? %>
      <%
        page = (cs_articles.current_page - 1)
        per_page = cs_articles.present? ? cs_articles.limit_value : 0
      %>
      <% cs_articles.each_with_index do |scr_article, index| %>
        <% ind = (page * per_page) + (index + 1) %>
        <tr id="scr_article_<%= scr_article.id %>">
          <td scope="row">
            <%= ind %>
          </td>
          <td>
            <div class="" style="max-height: 50px; overflow: hidden;">
              <%=raw scr_article.article.content %>
            </div>
          </td>
          <% if scr_article.chapter.present? %>
            <td><%= scr_article.chapter.name %> (<%= (scr_article.chapter.index) %>)</td>
          <% else %>
          <td>-</td>
          <% end %>
          <td>
            <%= scr_article.index %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6">
          <center>अभी कोई डाटा उपलब्ध नहीं है</center>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate cs_articles %>

app/views/admin/compiled_scriptures/add_articles_page.html.erb
<div class="" data-controller="admin-cscripture">
  <div class="row">
    <!-- <div class="col-md-1"></div> -->
    <div class="col-md-12">
      <div class="card">
        <div class="card-body h-100">
          <div class="row">
            <% if @scripture.chapters.present? %>
              <div class="col-md-8">
                <span class="text-start article-title text-primary" data-admin-cscripture-target="scripture" data-scripture-id="<%= @scripture.id %>">
                  उत्सव (<span class="text-success"><%= @scripture.name %></span>) में रचनाये जोड़े 
                </span>
              </div>
              <div class="col-md-4">
                <%= select_tag 'theme_chapters_name', options_from_collection_for_select(@scripture.chapters, "id", "name"), prompt: "अध्याय चुने", class:"form-control theme-chapter-name", 'data-admin-cscripture-target': 'chapter', 'data-action': 'change->admin-cscripture#searchArticlesByChapter' %>
              </div>
            <% else %>
              <div class="col-md-6">
                <span class="text-start article-title text-primary" data-admin-cscripture-target="scripture" data-scripture-id="<%= @scripture.id %>">
                  उत्सव (<span class="text-success"><%= @scripture.name %></span>) में रचनाये जोड़े 
                </span>
              </div>
              <div class="col-md-6 theme-chapter-bdr">
                आपने इस उत्सव (<%= @scripture.name %>) में कोई अध्याय नहीं जोड़ा है अगर आप अध्याय जोड़ना चाहते है तो यहाँ <a href="<%= admin_scripture_chapters_new_path(@scripture) %>">click</a> करे 
              </div>
            <% end %>
          </div>
          <div class="dropdown-divider"></div>
          <div class="search-block" data-action="click->admin-cscripture#isSearchEnable">
            <%= render 'search_options' %>
          </div>
        </div>
      </div>
    </div>
    <!-- <div class="col-md-1"></div> -->
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body h-100">
          <div class="row">
            <input type=hidden name="authenticity_token" value="<%= form_authenticity_token %>" data-admin-cscripture-target="csrfToken">
            <span class="text-primary chapter-article-header">
              <%= @theme_chapters.blank? ? "उत्सव में जोड़ी गयी रचनाये" : "उत्सव के अध्याय में जोड़ने के लिए उपलब्ध रचनाये"%>
            </span>
            <div class="dropdown-divider"></div>
            <ul class="list-group" id="article-list">
              <%= render partial: "article", locals: {articles: @articles} %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body h-100">
          <div class="row">
            <span class="text-primary chapter-article-header">
              <%= @theme_chapters.blank? ? "उत्सव में जोड़ी गयी रचनाये" : "उत्सव के अध्याय में जोड़ी गयी रचनाये"%>
            </span>
            <div class="dropdown-divider"></div>
            <ul class="list-group" id="added-article-list">
              <%= render partial: "added_article", locals: {cs_articles: @added_articles} %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%#= javascript_import_module_tag "custom/add-article-page-custom" %>
<% end %>

app/views/admin/compiled_scriptures/get_chapter_articles.js.erb
$("#article-list").html(`<%= escape_javascript(render 'indexed_article', cs_articles: @articles)%>`);

app/views/admin/compiled_scriptures/get_indexed_articles.js.erb
<% if params[:action_type] == 'Non-Indexed' %>
  $(".index-tgl").addClass("btn-secondary").removeClass("btn-primary");
  $(".non-index-tgl").removeClass("btn-secondary").addClass("btn-primary");
<% elsif params[:action_type] == 'Indexed' %>
  $(".non-index-tgl").addClass("btn-secondary").removeClass("btn-primary");
  $(".index-tgl").removeClass("btn-secondary").addClass("btn-primary");
<% end %>

$("#article-list").html(`<%= escape_javascript(render 'unindexed_article', cs_articles: @articles)%>`);

app/views/admin/compiled_scriptures/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          संकलित ग्रन्थ सूची
        </div>
        <div class="dropdown-divider"></div>
        <div id="compiled_scripture_list">
          <table class="table">
            <thead class="table-primary">
              <tr>
                <th>#</th>
                <th>संकलित ग्रन्थ नाम</th>
                <th>अध्याय जोड़े</th>
                <th>रचनाये जोड़े</th>
                <th>अनुक्रम अद्यतन</th>
              </tr>
            </thead>
            <tbody>
              <% if @scriptures.present? %>
                <% @scriptures.each_with_index do | scripture, index | %>
                  <tr>
                    <td><%= index + 1%></td>
                    <td>
                      <%= link_to scripture.name, admin_compiled_scripture_path(scripture) %>
                    </td>
                    <td>
                      <a href="<%= admin_scripture_chapters_new_path(scripture.id) %>" 
                        class="btn btn-primary text-white">
                        <i class="fa-solid fa-circle-plus fnt-sz-18"></i> अध्याय जोड़े
                      </a>
                    </td>
                    <td>
                      <a href="<%= admin_compiled_scripture_add_articles_page_path(scripture) %>" class="btn btn-primary text-white">
                        <i class="fa-solid fa-file-circle-plus fnt-sz-18"></i> रचनाये जोड़े
                      </a>
                    </td>
                    <td>
                      <%= form_tag admin_compiled_scripture_update_article_index_path(scripture) do | form | %>
                        <%= hidden_field_tag "bulk_updation", true %>
                        <button  type="submit" class="btn btn-primary text-white">
                          <i class="fa-solid fa-pencil fnt-sz-18"></i> एक साथ अनुक्रम अद्यतन
                        </button>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% else %>
              <% end %>
            </tbody>
          </table>
          <%= link_to "नया अध्याय", new_admin_chapter_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/compiled_scriptures/scriptures_for_indexing.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          संकलित ग्रन्थ सूची
        </div>
        <div class="dropdown-divider"></div>
        <div id="compiled_scripture_list">
          <table class="table">
            <thead class="table-primary">
              <tr>
                <th>#</th>
                <th>संकलित ग्रन्थ नाम</th>
                <th>अनुक्रम अद्यतन</th>
              </tr>
            </thead>
            <tbody>
              <% if @scriptures.present? %>
                <% @scriptures.each_with_index do | scripture, index | %>
                  <tr>
                    <td><%= index + 1%></td>
                    <td>
                      <%= link_to scripture.name, admin_compiled_scripture_path(scripture) %>
                    </td>
                    <td>
                      <a href="<%= edit_article_index_admin_compiled_scriptures_path(scripture) %>" class="btn btn-primary text-white">
                        <i class="fa-solid fa-pencil fnt-sz-18"></i> अनुक्रम अद्यतन
                      </a>
                    </td>
                  </tr>
                <% end %>
              <% else %>
              <% end %>
            </tbody>
          </table>
          <%= link_to "नया अध्याय", new_admin_chapter_path %>
        </div>
      </div>
    </div>
  </div>
</div>