config/routes.rb
Rails.application.routes.draw do
  #root to: "welcome#index"
  #root to: "homes#index"
  root to: "public/articles#index"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  resources :user_profiles do
    get "/comments" => "user_profiles#comments", as: :user_comments, on: :member
    get "/contexts" => "user_profiles#contexts", as: :user_contexts, on: :member
    get "/authors" => "user_profiles#authors", as: :user_authors, on: :member
    get "/articles" => "user_profiles#articles", as: :user_articles, on: :member
  end

  resources :homes, only: [:index] do
    get '/set_layout/:layout_name' => "homes#set_layout", as: :set_layout, on: :collection
  end

  resources :articles do
    get   "/tags" => "articles#tags", as: :tags, on: :member
    post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member
    get "/export_pdf" => "articles#article_pdf", as: :export_pdf, on: :member
    get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    get "/contribution/new" => "articles#contributed_article_new", as: :contributed_article_new, on: :collection
    post "contribution/create" => "articles#contributed_article_create", as: :contributed_article_create, on: :collection
  end

  resources :comments

  resources :themes do
    get "/theme_chapters/new" => "theme_chapters#new", as: :new_theme_chapter#, on: :member
    get "/add_articles_page" => "themes#add_articles_page", as: :add_articles_page , on: :member
    post "/add_article_in_theme" => "themes#add_article_in_theme", as: :add_article_in_theme, on: :member
    post "/remove_article_from_theme" => "themes#remove_article_from_theme", as: :remove_article_from_theme, on: :member
    get "/search_articles" => "themes#search_articles", as: :search_articles, on: :collection
  end
  resources :authors do
    get "/autocomplete_term" => "authors#autocomplete_term", as: :autocomplete_term, on: :collection
  end
  resources :theme_chapters
  resources :comment_reportings, only: [:index, :destroy, :create]
  post "comment_reportings/:comment_id/mark_as_read" => "comment_reportings#mark_as_read", as: :mark_as_read
  resources :tags
  resources :panchangs, only: [:index, :show] do
    get "/pdf/export" => "panchangs#panchang_pdf", as: :export_pdf, on: :member
  end
  
  resources :stories
  resources :search, only: [] do
    get "/autocomplete_term" => "search#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/articles" => "search#search_articles", as: :search_articles, on: :collection
  end

  namespace :admin do
    resources :dashboards, only: [:index] do
    end
    resources :user_mgmts, only: [:index, :show, :destroy] do
      post "/block_to_user" => "user_mgmts#block_to_user", as: :block_to_user, on: :member
      post "/unblock_to_user" => "user_mgmts#unblock_to_user", as: :unblock_to_user, on: :member
      get "/blocked_users" => "user_mgmts#blocked_users", as: :blocked_users, on: :collection
    end
    resources :article_types
    resources :contexts
    resources :articles, only: [:index, :show, :edit, :update, :destroy] do
      get   "/tags" => "articles#tags", as: :tags, on: :member
      post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member

      get "/approved" => "articles#approved", as: :approved_articles, on: :collection
      get "/pending" => "articles#pending", as: :pending_articles, on: :collection
      get "/rejected" => "articles#rejected", as: :rejected_articles, on: :collection
      post "/approve" => "articles#approve", as: :approve, on: :member
      post "/reject" => "articles#reject", as: :reject, on: :member
      
      get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
      get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    end
    resources :authors, only: [:index, :show, :edit, :update, :destroy] do
      get "/approved" => "authors#approved", as: :approved_authors, on: :collection
      get "/pending" => "authors#pending", as: :pending_authors, on: :collection
      post "/approve" => "authors#approve", as: :approve, on: :member
      post "/reject" => "authors#reject", as: :reject, on: :member
      post "/merge" => "authors#merge", as: :merge, on: :member
      post "/mark_as_sant" => "authors#mark_as_sant", as: :mark_as_sant, on: :member
      post "/remove_from_sant" => "authors#remove_from_sant", as: :remove_from_sant, on: :member
    end
    resources :reports, only: [:index] do
      get '/articles_report' => "reports#articles_report", as: :articles_report, on: :collection
      get '/authors_report' => "reports#authors_report", as: :authors_report, on: :collection
      get '/contexts_report' => "reports#contexts_report", as: :contexts_report, on: :collection
    end

    resources :tags, only: [:index, :show, :edit, :update, :destroy] do
      post "/reject" => "tags#reject", as: :reject, on: :member
      post "/approve" => "tags#approve", as: :approve, on: :member
      get "/approved" => "tags#approved", as: :approved_tags, on: :collection
      get "/rejected" => "tags#rejected", as: :rejected_tags, on: :collection
      post '/convert_tag_to_context' => "tags#convert_tag_to_context", as: :tag_to_context, on: :member
    end

    resources :suggestions, only: [:index, :show] do
      get "/approve" => "suggestions#approve", as: :approve, on: :member
      get "/reject" => "suggestions#reject", as: :reject, on: :member
      get "/approved" => "suggestions#approved", as: :approved, on: :collection
      get "/rejected" => "suggestions#rejected", as: :rejected, on: :collection
    end

    resources :panchangs do
      # get '/get_tithis' => "panchangs#get_tithis", on: :collection

      post '/populate_panchang' => "panchangs#populate_panchang", on: :member, as: :populate_panchang
      post '/add_purshottam_mas' => "panchangs#add_purshottam_mas", on: :member, as: :add_purshottam_mas
      post '/remove_purshottam_mas' => "panchangs#remove_purshottam_mas", on: :member, as: :remove_purshottam_mas

      resources :panchang_tithis do
        get '/:month_id/get_tithis' => "panchang_tithis#get_tithis", as: :get_tithis, on: :collection
      end
    end

    resources :scriptures do
      get "/chapters/new" => "chapters#new", as: :chapters_new
    end

    resources :compiled_scriptures, only: [:index, :show] do
      get '/get_articles' => "compiled_scriptures#get_articles", as: :get_articles
      get '/add_articles_page' => "compiled_scriptures#add_articles_page", as: :add_articles_page
      post '/add_article' => "compiled_scriptures#add_article", as: :add_articles
      post '/remove_article' => "compiled_scriptures#remove_article", as: :remove_articles
      get '/search_articles' => "compiled_scriptures#search_articles", as: :search_articles, on: :collection

      get '/scriptures_for_indexing' => "compiled_scriptures#scriptures_for_indexing", as: :scriptures_for_indexing, on: :collection
      get '/:scripture_id/edit_article_index' => "compiled_scriptures#edit_article_index", as: :edit_article_index, on: :collection
      get '/get_chapter_articles' => "compiled_scriptures#get_chapter_articles", as: :get_chapter_articles
      get '/update_articles_index' => "compiled_scriptures#update_articles_index", as: :update_articles_index
      
      get '/get_indexed_articles' => "compiled_scriptures#get_indexed_articles", as: :get_indexed_articles
      post '/update_article_index' => "compiled_scriptures#update_article_index", as: :update_article_index
    end

    resources :chapters do 
      get '/get_sections' => "chapters#get_sections", as: :get_sections, on: :collection
      get '/get_section_chapters' => "chapters#get_section_chapters", as: :get_section_chapters, on: :collection
      get '/add_section_chapters' => "chapters#add_section_chapters", as: :add_section_chapters, on: :collection
      get '/remove_section_chapters' => "chapters#remove_section_chapters", as: :remove_section_chapters, on: :collection
      post '/add_chapters_in_section' => "chapters#add_chapters_in_section", as: :add_chapters_in_section, on: :collection
      post '/remove_chapters_from_section' => "chapters#remove_chapters_from_section", as: :remove_chapters_from_section, on: :collection
    end
    resources :scripture_articles do
      get '/get_chapters' => "scripture_articles#get_chapters", as: :get_chapters, on: :collection
      get '/get_index' => "scripture_articles#get_index", as: :get_index, on: :collection
      get '/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      # get '/:scripture_type/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      post '/update_article_index' => "scripture_articles#update_article_index", as: :update_article_index, on: :collection
      get '/get_chapter_articles' => "scripture_articles#get_chapter_articles", as: :get_chapter_articles, on: :collection
    end

    resources :strota do 
      resources :strota_articles do 
        # get '/add_aarti' => 'strota_articles#new', as: :add_aarti, on: :member
        # get '/get_strota_articles' => 'strota_articles#get_strota_articles', as: :get_strota_articles, on: :member
        # get '/get_index' => "strota_articles#get_index", as: :get_index, on: :collection
        get '/edit_article_index' => "strota_articles#edit_article_index", as: :edit_article_index, on: :collection
        post '/update_article_index' => "strota_articles#update_article_index", as: :update_article_index, on: :member
      end
    end
  end

  namespace :public, path: :pb do

    resources :articles, only: [:index, :show] do

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles_by_count = Article.group_by_day(:created_at).count
    @articles_by_type = ArticleType.joins(:articles).group(:name).count
    @artcles_by_context = Context.joins(:articles).group(:name).count
    @contexts_by_approval = {pending: Context.pending.length, approved: Context.approved.length}
    @articles_pending = Article.pending
    @authors_pending = Author.pending
    @authors_approved = Author.approved

    articles_grouped = Article.group(:is_approved).count
    authors_grouped = Author.group(:is_approved).count
    tags_grouped = Tag.group(:is_approved).count
    @spam_comment_reports = CommentReporting.not_read

    @articles_group_by_approval = {
      approved: articles_grouped[true] ? articles_grouped[true] : 0,
      pending: articles_grouped[nil] ? articles_grouped[nil] : 0
    }
    @authors_group_by_approval = {
      approved: authors_grouped[true] ? authors_grouped[true] : 0,
      pending: authors_grouped[nil] ? authors_grouped[nil] : 0
    }
    @tags_group_by_approval = {
      approved: tags_grouped[true] ? tags_grouped[true] : 0,
      pending: tags_grouped[nil] ? tags_grouped[nil] : 0
    }

    @registered_users = User.where("role_id > ?", 2)
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="row">
	<div class="col-md-7">
		<div class="row">
			<div class="col-md-4">
				<div class="card">
					<div class="card-body h-225">
						<div class="row">
							<div class="col mt-0">
								<h5 class="card-title">Articles</h5>
							</div>
							<div class="col-auto">
								<div class="stat-new text-primary">
									<i class="fa-solid fa-file"></i>
								</div>
							</div>
						</div>
						<br/>
						<div class="mb-3">
							<a href="<%= admin_articles_path %>" class="btn btn-primary mb-2 m-w-120">
								Total:&nbsp;<%= @articles_group_by_approval[:approved] +  @articles_group_by_approval[:pending] %>
							</a>
							<a href="<%= approved_articles_admin_articles_path %>" class="btn btn-success mb-2 m-w-120">
								Approved:&nbsp;<%= @articles_group_by_approval[:approved] %>
							</a>
							<a href="<%= pending_articles_admin_articles_path %>" class="btn btn-warning m-w-120">
								Pending:&nbsp;<%= @articles_group_by_approval[:pending] %>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card">
					<div class="card-body h-225">
						<div class="row">
							<div class="col mt-0">
								<h5 class="card-title">Authors</h5>
							</div>
							<div class="col-auto">
								<div class="stat-new text-primary">
									<i class="fa-solid fa-user"></i>
								</div>
							</div>
						</div>
						<br/>
						<div class="mb-3">
							<a href="<%= admin_authors_path %>" class="btn btn-primary mb-2 m-w-120">
								Total:&nbsp;<%= @authors_group_by_approval[:approved] +  @authors_group_by_approval[:pending] %>
							</a>
							<a href="<%= approved_authors_admin_authors_path %>" class="btn btn-success mb-2 m-w-120">
								Approved:&nbsp;<%= @authors_group_by_approval[:approved] %>
							</a>
							<a href="<%= pending_authors_admin_authors_path %>" class="btn btn-warning m-w-120">
								Pending:&nbsp;&nbsp;&nbsp;<%= @authors_group_by_approval[:pending] %>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card">
					<div class="card-body">
						<div class="row">
							<div class="col mt-0">
								<h5 class="card-title">Tags</h5>
							</div>
							<div class="col-auto">
								<div class="stat-new text-primary">
									<i class="fa-solid fa-tags"></i>
								</div>
							</div>
						</div>
						<br/>
						<div class="mb-3">
							<a href="<%= admin_contexts_path %>" class="btn btn-primary mb-2 m-w-120">
								Total:&nbsp;<%= @tags_group_by_approval[:approved] +  @tags_group_by_approval[:pending] %>
							</a>
							<a href="<%= approved_tags_admin_tags_path %>" class="btn btn-success mb-2 m-w-120">
								Approved:&nbsp;<%= @tags_group_by_approval[:approved] %>
							</a>
							<a href="<%= rejected_tags_admin_tags_path %>" class="btn btn-warning m-w-120">
								Pending:&nbsp;&nbsp;&nbsp;<%= @tags_group_by_approval[:pending] %>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-5">
		<div class="row">
			<div class="col-md-6">
				<div class="card">
					<div class="card-body h-225">
						<div class="row">
							<div class="col mt-0">
								<h5 class="card-title">Comments Spam Report</h5>
							</div>
							<div class="col-auto">
								<div class="stat-new text-primary">
									<i class="fa-solid fa-comment-slash"></i>
								</div>
							</div>
						</div>
						<br/>
						<div class="mb-3">
							<a href="<%= comment_reportings_path %>" class="btn btn-danger m-w-120">
								Reported Spam Comments:&nbsp;<%= @spam_comment_reports.count %>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card">
					<div class="card-body h-225">
						<div class="row">
							<div class="col mt-0">
								<h5 class="card-title">User Mgmt Report</h5>
							</div>
							<div class="col-auto">
								<div class="stat-new text-primary">
									<i class="fa-solid fa-user"></i>
								</div>
							</div>
						</div>
						<br/>
						<div class="mb-3">
							<a href="<%= admin_user_mgmts_path %>" class="btn btn-danger m-w-120">
								Registered User:&nbsp;<%= @registered_users.count %>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="card">
			<div class="card-body h-400">
				<%= pie_chart @contexts_by_approval, title: "प्रसंग रिपोर्ट" %>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="card">
			<div class="card-body h-400">
				<%= line_chart @articles_by_count, xtitle: "Date", ytitle: "रचना संख्या", title: "रचनायें: समय आधारित रिपोर्ट" %>
				<%#= column_chart @article_by_counts, xtitle: "Date", ytitle: "रचना संख्या" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="card">
			<div class="card-body h-400">
				<%= pie_chart @articles_by_type, title: "रचनायें: प्रकार आधारित रिपोर्ट" %>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="card">
			<div class="card-body h-400">
				<%= column_chart @artcles_by_context, title: "रचनायें: प्रसंग आधारित रिपोर्ट	" %>
				<%#= column_chart @article_by_counts, xtitle: "Date", ytitle: "रचना संख्या" %>
			</div>
		</div>
	</div>
</div>

<div class="row" data-controller="dashboard">
	<div class="col-md-6">
		<%#= render "pending_contexts", contexts_pending: @contexts_pending,
			contexts_approved: @contexts_approved %>
		<div class="card">
			<div class="card-body h-450">
		    <div class="col-md-12 page-subject-header">
          <span>लंबित रचना सूची</span>
        </div>
		    <div class="dropdown-divider"></div>
		    <table class="table">
		      <thead class="table-primary ps-0 pe-0">
		        <tr>
		          <th scope="col">S. No.</th>
		          <th scope="col">नई रचनायें</th>
		        </tr>
		      </thead>
		      <tbody>
		      	<% if @articles_pending.present? %>
		          <% @articles_pending.limit(5).each_with_index do |article, index| %>
		            <tr>
		              <th><%= index+1 %></th>
		              <td>
		              	<%= article.hindi_title %>
		              </td>
		          	</tr>
		          <% end %>
		        <% else %>
		          <td colspan="4">
		          	अभी रिकॉर्ड उपलब्ध नहीं है.
		          </td>
		        <% end %>
						<tr>
							<td colspan="5">
								<a href="<%= pending_articles_admin_articles_path %>" class="fRight">
									स्वीकृत करने/और पढ़ने के लिए यहाँ क्लिक करे
								</a>
							</td>
						</tr>
		      </tbody>
		    </table>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<%#= render "pending_authors", authors_pending: @authors_pending,
			authors_approved: @authors_approved %>
		<div class="card">
		<div class="card-body h-450">
	    <div class="col-md-12 page-subject-header">
        <span>लंबित रचनाकार / कवि / भक्त सूची</span>
      </div>
	    <div class="dropdown-divider"></div>
	    <table class="table">
	      <thead class="table-primary">
	        <tr>
	          <th scope="col">S. No.</th>
	          <th scope="col">नए रचनाकार</th>
	        </tr>
	      </thead>
	      <tbody>
	      	<% if @authors_pending.present? %>
	          <% @authors_pending.limit(5).each_with_index do |author, index| %>
	            <tr>
	            	<th><%= index +1 %></th>
	            	<td>
	            		<%= author.name %> </td>
	            </tr>
	          <% end %>
	        <% else %>
	          <td colspan="3">
	          	अभी रिकॉर्ड उपलब्ध नहीं है.
	          </td>
	        <% end %>
					<tr>
						<td colspan="5">
							<a href="<%= pending_authors_admin_authors_path %>" class="fRight">
								स्वीकृत करने/और पढ़ने के लिए यहाँ क्लिक करे
							</a>
						</td>
					</tr>
	      </tbody>
	    </table>
		</div>
	</div>
	</div>
</div>