config/routes.rb
Rails.application.routes.draw do
  #root to: "welcome#index"
  #root to: "homes#index"
  root to: "public/articles#index"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  resources :user_profiles do
    get "/comments" => "user_profiles#comments", as: :user_comments, on: :member
    get "/contexts" => "user_profiles#contexts", as: :user_contexts, on: :member
    get "/authors" => "user_profiles#authors", as: :user_authors, on: :member
    get "/articles" => "user_profiles#articles", as: :user_articles, on: :member
  end

  resources :homes, only: [:index] do
    get '/set_layout/:layout_name' => "homes#set_layout", as: :set_layout, on: :collection
  end

  resources :articles do
    get   "/tags" => "articles#tags", as: :tags, on: :member
    post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member
    get "/export_pdf" => "articles#article_pdf", as: :export_pdf, on: :member
    get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    get "/contribution/new" => "articles#contributed_article_new", as: :contributed_article_new, on: :collection
    post "contribution/create" => "articles#contributed_article_create", as: :contributed_article_create, on: :collection
  end

  resources :comments

  resources :themes do
    get "/theme_chapters/new" => "theme_chapters#new", as: :new_theme_chapter#, on: :member
    get "/add_articles_page" => "themes#add_articles_page", as: :add_articles_page , on: :member
    post "/add_article_in_theme" => "themes#add_article_in_theme", as: :add_article_in_theme, on: :member
    post "/remove_article_from_theme" => "themes#remove_article_from_theme", as: :remove_article_from_theme, on: :member
    get "/search_articles" => "themes#search_articles", as: :search_articles, on: :collection
  end
  resources :authors do
    get "/autocomplete_term" => "authors#autocomplete_term", as: :autocomplete_term, on: :collection
  end
  resources :theme_chapters
  resources :comment_reportings, only: [:index, :destroy, :create]
  post "comment_reportings/:comment_id/mark_as_read" => "comment_reportings#mark_as_read", as: :mark_as_read
  resources :tags
  resources :panchangs, only: [:index, :show] do
    get "/pdf/export" => "panchangs#panchang_pdf", as: :export_pdf, on: :member
  end
  
  resources :stories
  resources :search, only: [] do
    get "/autocomplete_term" => "search#autocomplete_term", as: :autocomplete_term, on: :collection
    get "/articles" => "search#search_articles", as: :search_articles, on: :collection
  end

  namespace :admin do
    resources :dashboards, only: [:index] do
    end
    resources :user_mgmts, only: [:index, :show, :destroy] do
      post "/block_to_user" => "user_mgmts#block_to_user", as: :block_to_user, on: :member
      post "/unblock_to_user" => "user_mgmts#unblock_to_user", as: :unblock_to_user, on: :member
      get "/blocked_users" => "user_mgmts#blocked_users", as: :blocked_users, on: :collection
    end
    resources :article_types
    resources :contexts
    resources :articles, only: [:index, :show, :edit, :update, :destroy] do
      get   "/tags" => "articles#tags", as: :tags, on: :member
      post  "/tags_update" => "articles#tags_update", as: :tags_update, on: :member

      get "/approved" => "articles#approved", as: :approved_articles, on: :collection
      get "/pending" => "articles#pending", as: :pending_articles, on: :collection
      get "/rejected" => "articles#rejected", as: :rejected_articles, on: :collection
      post "/approve" => "articles#approve", as: :approve, on: :member
      post "/reject" => "articles#reject", as: :reject, on: :member
      
      get "/autocomplete_term" => "articles#autocomplete_term", as: :autocomplete_term, on: :collection
      get "/search_articles" => "articles#search_articles", as: :search_articles, on: :collection
    end
    resources :authors, only: [:index, :show, :edit, :update, :destroy] do
      get "/approved" => "authors#approved", as: :approved_authors, on: :collection
      get "/pending" => "authors#pending", as: :pending_authors, on: :collection
      post "/approve" => "authors#approve", as: :approve, on: :member
      post "/reject" => "authors#reject", as: :reject, on: :member
      post "/merge" => "authors#merge", as: :merge, on: :member
      post "/mark_as_sant" => "authors#mark_as_sant", as: :mark_as_sant, on: :member
      post "/remove_from_sant" => "authors#remove_from_sant", as: :remove_from_sant, on: :member
    end
    resources :reports, only: [:index] do
      get '/articles_report' => "reports#articles_report", as: :articles_report, on: :collection
      get '/authors_report' => "reports#authors_report", as: :authors_report, on: :collection
      get '/contexts_report' => "reports#contexts_report", as: :contexts_report, on: :collection
    end

    resources :tags, only: [:index, :show, :edit, :update, :destroy] do
      post "/reject" => "tags#reject", as: :reject, on: :member
      post "/approve" => "tags#approve", as: :approve, on: :member
      get "/approved" => "tags#approved", as: :approved_tags, on: :collection
      get "/rejected" => "tags#rejected", as: :rejected_tags, on: :collection
      post '/convert_tag_to_context' => "tags#convert_tag_to_context", as: :tag_to_context, on: :member
    end

    resources :suggestions, only: [:index, :show] do
      get "/approve" => "suggestions#approve", as: :approve, on: :member
      get "/reject" => "suggestions#reject", as: :reject, on: :member
      get "/approved" => "suggestions#approved", as: :approved, on: :collection
      get "/rejected" => "suggestions#rejected", as: :rejected, on: :collection
    end

    resources :panchangs do
      # get '/get_tithis' => "panchangs#get_tithis", on: :collection

      post '/populate_panchang' => "panchangs#populate_panchang", on: :member, as: :populate_panchang
      post '/add_purshottam_mas' => "panchangs#add_purshottam_mas", on: :member, as: :add_purshottam_mas
      post '/remove_purshottam_mas' => "panchangs#remove_purshottam_mas", on: :member, as: :remove_purshottam_mas

      resources :panchang_tithis do
        get '/:month_id/get_tithis' => "panchang_tithis#get_tithis", as: :get_tithis, on: :collection
      end
    end

    resources :scriptures do
      get "/chapters/new" => "chapters#new", as: :chapters_new
    end

    resources :compiled_scriptures, only: [:index, :show] do
      get '/get_articles' => "compiled_scriptures#get_articles", as: :get_articles
      get '/add_articles_page' => "compiled_scriptures#add_articles_page", as: :add_articles_page
      post '/add_article' => "compiled_scriptures#add_article", as: :add_articles
      post '/remove_article' => "compiled_scriptures#remove_article", as: :remove_articles
      get '/search_articles' => "compiled_scriptures#search_articles", as: :search_articles, on: :collection

      get '/scriptures_for_indexing' => "compiled_scriptures#scriptures_for_indexing", as: :scriptures_for_indexing, on: :collection
      get '/:scripture_id/edit_article_index' => "compiled_scriptures#edit_article_index", as: :edit_article_index, on: :collection
      get '/get_chapter_articles' => "compiled_scriptures#get_chapter_articles", as: :get_chapter_articles
      get '/update_articles_index' => "compiled_scriptures#update_articles_index", as: :update_articles_index
      
      get '/get_indexed_articles' => "compiled_scriptures#get_indexed_articles", as: :get_indexed_articles
      post '/update_article_index' => "compiled_scriptures#update_article_index", as: :update_article_index
    end

    resources :chapters do 
      get '/get_sections' => "chapters#get_sections", as: :get_sections, on: :collection
      get '/get_section_chapters' => "chapters#get_section_chapters", as: :get_section_chapters, on: :collection
      get '/add_section_chapters' => "chapters#add_section_chapters", as: :add_section_chapters, on: :collection
      get '/remove_section_chapters' => "chapters#remove_section_chapters", as: :remove_section_chapters, on: :collection
      post '/add_chapters_in_section' => "chapters#add_chapters_in_section", as: :add_chapters_in_section, on: :collection
      post '/remove_chapters_from_section' => "chapters#remove_chapters_from_section", as: :remove_chapters_from_section, on: :collection
    end
    resources :scripture_articles do
      get '/get_chapters' => "scripture_articles#get_chapters", as: :get_chapters, on: :collection
      get '/get_index' => "scripture_articles#get_index", as: :get_index, on: :collection
      get '/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      # get '/:scripture_type/edit_article_index' => "scripture_articles#edit_article_index", as: :edit_article_index, on: :collection
      post '/update_article_index' => "scripture_articles#update_article_index", as: :update_article_index, on: :collection
      get '/get_chapter_articles' => "scripture_articles#get_chapter_articles", as: :get_chapter_articles, on: :collection
    end

    resources :strota do 
      resources :strota_articles do 
        # get '/add_aarti' => 'strota_articles#new', as: :add_aarti, on: :member
        # get '/get_strota_articles' => 'strota_articles#get_strota_articles', as: :get_strota_articles, on: :member
        # get '/get_index' => "strota_articles#get_index", as: :get_index, on: :collection
        get '/edit_article_index' => "strota_articles#edit_article_index", as: :edit_article_index, on: :collection
        post '/update_article_index' => "strota_articles#update_article_index", as: :update_article_index, on: :member
      end
    end
  end

  namespace :public, path: :pb do

    resources :articles, only: [:index, :show] do

app/models/chapter.rb
class Chapter < ApplicationRecord

  belongs_to :scripture
  has_many :scripture_articles
  has_many :cs_articles
  has_many :articles, :through => :cs_articles

  has_many :chapters, foreign_key: 'parent_id', class_name: 'Chapter'
  belongs_to :section, foreign_key: 'parent_id', class_name: 'Chapter', optional: true  

  scope :chapter_scope, ->() { where(is_section: false) }
  scope :section_scope, ->() { where(is_section: true) }
  scope :chapters, ->() { where(is_section: false) }

  validates :name, presence: true

  paginates_per 10

end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :set_chapter, only: %i[ show edit update destroy ]

  def index
    @chapters = Chapter.chapters.order("name ASC").page(params[:page])
  end

  def new
    @scriptures = current_user.scriptures
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    @scriptures = current_user.scriptures

    respond_to do |format|
      if @chapter.save
        if @chapter.is_section == true
          format.html { redirect_to admin_scripture_path(@chapter.scripture.id) }
        else
          format.html { redirect_to admin_chapters_url(is_section: params[:is_section]), notice: "अध्याय को सफलतापूर्वक बना दिया गया है |" }
        end
        format.json { render :show, status: :created, location: @chapter }
      else
        params[:scripture_id] = params[:chapter][:scripture_id]
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
    @scriptures = current_user.scriptures
    @scripture = @chapter.scripture
    @sections = @scripture.sections
  end

  def update

    respond_to do |format|
      if @chapter.update(chapter_params)
        if @chapter.is_section == true
          format.html { redirect_to admin_scripture_path(@chapter.scripture.id) }
        else
          format.html { redirect_to admin_chapters_url, notice: "अध्याय को सफलतापूर्वक अद्यतित कर दिया गया है |" }
        end
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    is_section = @chapter.is_section
    @chapter.destroy

    respond_to do |format|
      if is_section == true
        format.html { redirect_to admin_scripture_path(@chapter.scripture.id) }
      else
        format.html { redirect_to admin_chapters_url, notice: "अध्याय को सफलतापूर्वक को डिलीट कर दिया गया है | " }
      end

      format.json { head :no_content }
    end
  end
  
  def add_section_chapters
    @scriptures = Scripture.all
  end

  def remove_section_chapters
    @scriptures = Scripture.all
  end

  def get_sections
    @scripture = current_user.scriptures.find(params[:scripture_id]) rescue nil
    @sections = @scripture.sections rescue nil
    @chapters = @scripture.chapters.where("is_section is false and parent_id is null") rescue nil
  end

  def get_section_chapters
    @section = Chapter.find(params[:section_id])
    @chapters = @section.chapters
  end

  def add_chapters_in_section
    Chapter.where("id in (?)", params[:chapters]).update(parent_id: params[:section_id])
    @scripture = Scripture.find(params[:scripture_id])
    @chapters = @scripture.chapters.where("is_section is false and parent_id is null")
  end

  def remove_chapters_from_section
    Chapter.where("id in (?)", params[:chapters]).update(parent_id: nil)
    @section = Chapter.find(params[:section_id]) rescue nil
    @chapters = @section.chapters rescue nil
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.fetch(:chapter, {}).permit(:name, :is_section, :parent_id, :scripture_id, :index)
    end

    def verify_admin
      if !current_user.is_admin && !current_user.is_super_admin
        redirect_back_or_to homes_path
      end
    end
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/views/admin/chapters/_chapter.html.erb
<table class="table">
  <thead class="table-primary">
    <tr>
      <th>S. No.</th>
      <th>अध्याय का नाम</th>
      <th>सेक्शन का नाम</th>
      <th>रसिक वाणी/ग्रन्थ का नाम</th>
      <th>रचना जोड़े</th>
      <th>गतिविधि</th>
    </tr>
  </thead>
  <tbody>
    <% if chapters.present? %>
      <%
        page = (chapters.current_page - 1)
        per_page = chapters.present? ? chapters.limit_value : 0
      %>
      <% chapters.each_with_index do |chapter, index| %>
        <% ind = (page * per_page) + (index + 1) %>
        <tr>
          <td scope="row">
            <%= ind %>
          </td>
          <td>
            <strong>
              <%= chapter.name %>
            </strong>
          </td>
          <td>
            <%= chapter.section.present? ? chapter.section.name : '-' %>
          </td>
          <td>
            <% scripture = chapter.scripture %>
            <%= link_to scripture.name, admin_scripture_path(scripture.id) %>
          </td>
          <td>
            <%= link_to new_admin_scripture_article_path, class: "btn btn-primary" do %>
              <i class="fa-solid fa-file-circle-plus"></i> रचना जोड़े
            <% end %>
          </td>
          <td>
            <%= link_to edit_admin_chapter_path(chapter) do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= button_to '<i class="fa fa-trash" style="color:red;"></i>'.html_safe, admin_chapter_path(chapter), method: :delete, style: "border: 0px", form: {class: 'ps-0 pe-0', style: "display:inline-block; font-size: 18px;"} %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6">
          <center>अभी कोई डाटा उपलब्ध नहीं है</center>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if paginate(chapters).present? %>
  <%= paginate chapters, remote: true %>
  <div class="dropdown-divider"></div>
<% end %>

app/views/admin/chapters/_form.html.erb
<%= form_with(model: [:admin, chapter]) do |form| %>
  <div class="row">
    <div class="mb-3 alert alert-danger alert-dismissible fade show" style="display:  <%= chapter.errors.present? ? 'block' : 'none' %>;" role="alert">
      <% chapter.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      <button type="button" class="btn-close" onclick="$('.alert').hide()" aria-label="Close" style="font-size: 12px; "></button>
    </div>

    <div class='mb-3'>
      <label class='form-label'>
        रसिक वाणी/ग्रन्थ <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
      </label>
      <% 
        scirpture_list = @scriptures.collect{|scrptr| [scrptr.name, scrptr.id]}
        scripture_id = form.object.id.present? ? @chapter.scripture_id : params[:scripture_id]
      %>
      <%= form.select :scripture_id, options_for_select(scirpture_list, scripture_id), {prompt: 'रसिक ग्रन्थ/वाणी को चुनिये'}, 
        class: 'form-control', 'data-action': 'change->admin-chapter#getSections' %>
    </div>

    <div class='mb-3'>
      <label class='form-label'>
        अध्याय का शीर्षक <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
      </label>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class='mb-3'>
      <label class='form-label'>
        अध्याय का अनुक्रम <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
      </label>
      <%= form.text_field :index, class: 'form-control' %>
    </div>

    <div class='text-center mt-3 actions'>
      <div class="row">
        <div class="col-md-4">
          <% if form.object.id.blank? %>
            <%= form.submit "अध्याय जोड़े", class: 'btn btn-lg btn-primary form-control' %>
          <% else %>
            <%= form.submit "अध्याय अद्यतन करे", class: 'btn btn-lg btn-primary form-control' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/chapters/_section_form.html.erb
<%= form_with(model: [:admin, chapter]) do |form| %>
  <div class="row">
    <div class="mb-3 alert alert-danger alert-dismissible fade show" style="display:  <%= chapter.errors.present? ? 'block' : 'none' %>;" role="alert">
      <% chapter.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      <button type="button" class="btn-close" onclick="$('.alert').hide()" aria-label="Close" style="font-size: 12px; "></button>
    </div>
    <%= hidden_field_tag :is_section, true%>
    <div class='mb-3'>
      <label class='form-label'>
        रसिक वाणी/ग्रन्थ <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
      </label>
      <% 
        scirpture_list = @scriptures.map{|scrptr| [scrptr.name, scrptr.id]}
      %>
      <%= form.select :scripture_id, options_for_select(scirpture_list, scripture_id), {prompt: 'रसिक ग्रन्थ/वाणी को चुनिये'}, 
        class: 'form-control' %>
    </div>
    
    <%= form.hidden_field :is_section, value: true, class: 'form-control' %>

    <div class='mb-3'>
      <label class='form-label'>
        सेक्शन का नाम <i class="fa fa-asterisk req-field" aria-hidden="true"></i>
      </label>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class='text-center mt-3 actions'>
      <div class="row">
        <div class="col-md-4">
          <% if form.object.id.blank? %>
            <%= form.submit "अध्याय जोड़े", class: 'btn btn-lg btn-primary form-control' %>
          <% else %>
            <%= form.submit "अध्याय अद्यतन करे", class: 'btn btn-lg btn-primary form-control' %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
<% end %>

app/views/admin/chapters/add_chapters_in_section.js.erb
<% if @chapters.present? %>
  var chapters_str = '';
  <% @chapters && @chapters.each do |chapter|%>
    chapters_str += `<div class="chapter-element" data-action="click->admin-chapter#updateCheckboxStatus">
      <input class="form-check-input" type="checkbox" 
        data-admin-chapter-target="chapter"
        value="<%= chapter.id %>" id="chapter-<%=chapter.id%>">
        <label for="chapter-<%=chapter.id%>">
          <%= chapter.name %>
        </label>
    </div>`
  <% end %>
  $("#chapter-block").html(chapters_str);
<% else %>
  $("#chapter-block").html('इस रसिक वाणी/ग्रन्थ के सभी अध्याय लिंक किये जा चुके है');
<% end %>

app/views/admin/chapters/add_section_chapters.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          सेक्शन में अध्याय जोड़े
        </div>
        <div class="dropdown-divider"></div>
        <div class="m-sm-4" data-controller= 'admin-chapter'>
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"  data-admin-chapter-target="csrfToken">
          <div class='mb-3'>
            <%= hidden_field_tag 'action_type', 'add_chapter', class:"form-control", 'data-admin-chapter-target': 'actionType' %>
          </div>
          <div class='mb-3'>
            <label class='form-label'>
              रसिक वाणी/ग्रन्थ
            </label>
            <%= select_tag 'scripture', options_from_collection_for_select(@scriptures, "id", "name"), :prompt => "रसिक ग्रन्थ/वाणी चुने", class:"form-control", 'data-admin-chapter-target': 'scripture', 'data-action': 'change->admin-chapter#getSections' %>
          </div>
          <div class='mb-3'>
            <label class='form-label'>
              सेक्शन
            </label>
            <%= select_tag 'section', options_for_select([]), :prompt => "सेक्शन चुने", class:"form-control", 'data-admin-chapter-target': 'section' %>
          </div>
          <div class='mb-3'>
            <div id="chapter-block" class="p-sm-2">
            </div>
          </div>
          <div class='mb-3'>
            <div class="col-md-3">
              <input type="button" class="form-control btn btn-primary" value="सेक्शन में अध्याय जोड़े" 
                data-action="click->admin-chapter#addChaptersInSection" />
            </div>
            <!-- <div class="row">
              <div class="col-md-3">
                <input type="button" class="form-control btn btn-primary" value="सेक्शन में अध्याय जोड़े" 
                  data-action="click->admin-chapter#addChaptersInSection" />
              </div>
              <div class="col-md-3">
                <input type="button" class="form-control btn btn-danger" value="सेक्शन से अध्याय हटायें" 
                  data-action="click->admin-chapter#removeChaptersFromSection" />
              </div>
            </div> -->
          </div>
        </div>
        <div class="dropdown-divider"></div>
      </div>
    </div>
  </div>
</div>

app/views/admin/chapters/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          <%= @chapter.is_section ? 'सेक्शन अद्यतन फॉर्म': 'अध्याय अद्यतन फॉर्म' %>
        </div>
        <div class="dropdown-divider"></div>
        <div class="m-sm-4">
          <% if @chapter.is_section %>
            <%= render "section_form", chapter: @chapter, scripture_id: @scripture.id %>
          <% else %>
            <%= render "form", chapter: @chapter, sections: @sections %>
          <% end %>
        </div>
        <%= link_to "रसिक वाणी/ग्रन्थ सूची देखे", admin_chapters_path %>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/chapter-custom" %>
<% end %>

app/views/admin/chapters/get_section_chapters.js.erb
<% if @chapters.present? %>
  var chapters_str = '';
  <% @chapters && @chapters.each do |chapter|%>
    chapters_str += `<div class="chapter-element" data-action="click->admin-chapter#updateCheckboxStatus">
      <input class="form-check-input" type="checkbox" data-admin-chapter-target="chapter"
        value="<%= chapter.id %>" checked id="chapter-<%=chapter.id%>">
        <label for="chapter-<%=chapter.id%>">
          <%= chapter.name %>
        </label>
    </div>`
  <% end %>
  $("#chapter-block").html(chapters_str);
<% else %>
   $("#chapter-block").html('');
<% end %>

app/views/admin/chapters/get_sections.js.erb
var options = '<option value="">सेक्शन को चुनिये</option>';
<% @sections && @sections.each do | section | %>
  options = options + '<option value="<%= section.id %>"><%= section.name %></option>'
<% end %>
$("#section").html(options);

<% if @chapters.present? and params[:action_type] == "add_chapter" %>
  var chapters_str = '';
  <% @chapters && @chapters.each do |chapter|%>
    chapters_str += `<div class="chapter-element" data-action="click->admin-chapter#updateCheckboxStatus">
      <input class="form-check-input" type="checkbox" 
        data-admin-chapter-target="chapter"
        value="<%= chapter.id %>" id="chapter-<%=chapter.id%>">
        <label for="chapter-<%=chapter.id%>">
          <%= chapter.name %>
        </label>
    </div>`
  <% end %>
  $("#chapter-block").html(chapters_str);
<% else %>
   $("#chapter-block").html('');
<% end %>

app/views/admin/chapters/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          रसिक वाणी/ग्रन्थ अध्याय सूची
        </div>
        <div class="dropdown-divider"></div>
        <div id="scripture_list">
          <%= render "chapter", chapters: @chapters %>
          <%= link_to "नया अध्याय", new_admin_chapter_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/chapters/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="col-md-12 page-subject-header">
          <%= params[:scripture_id].present? ? 'सेक्शन फॉर्म': 'अध्याय फॉर्म' %>
        </div>
        <div class="dropdown-divider"></div>
        <div class="m-sm-4" data-controller="admin-chapter">
          <% if params[:scripture_id].present? %>
            <%= render "section_form", chapter: @chapter, scripture_id: params[:scripture_id] %>
          <% else %>
            <%= render "form", chapter: @chapter, sections: nil %>
          <% end %>
        </div>
        <div class="dropdown-divider"></div>
        <%= link_to "अध्याय की सूची देखे", admin_chapters_path %>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/chapter-custom" %>
<% end %>

app/views/admin/chapters/remove_chapters_from_section.js.erb
<% if @chapters.present? %>
  var chapters_str = '';
  <% @chapters && @chapters.each do |chapter|%>
    chapters_str += `<div class="chapter-element" data-action="click->admin-chapter#updateCheckboxStatus">
      <input class="form-check-input" type="checkbox" data-admin-chapter-target="chapter"
        value="<%= chapter.id %>" checked id="chapter-<%=chapter.id%>">
        <label for="chapter-<%=chapter.id%>">
          <%= chapter.name %>
        </label>
    </div>`
  <% end %>
  $("#chapter-block").html(chapters_str);
<% else %>
  $("#chapter-block").html('इस सेक्शन में कोई भी अध्याय नहीं है');
<% end %>